export default {
  LOGIN: 'LOGIN',
  SIGN_UP: 'SIGN_UP',
  PERSIST_LOGIN: 'PERSIST_LOGIN',
  ACTIVE_ROUTE: 'ACTIVE_ROUTE',
  TOGGLE_SIDE_NAV: 'TOGGLE_SIDE_NAV',
  CREATE_STORY: 'CREATE_STORY',
  RESET: 'RESET',
  GET_STORIES: 'GET_STORIES',
  LOGOUT: 'LOGOUT',
  UPDATE_STORY_STATUS: 'UPDATE_STORY_STATUS',
};
