export default {
  LOGIN: 'LOGIN',
  PERSIST_LOGIN: 'PERSIST_LOGIN',
  ACTIVE_ROUTE: 'ACTIVE_ROUTE',
  TOGGLE_SIDE_NAV: 'TOGGLE_SIDE_NAV',
  CREATE_STORY: 'CREATE_STORY',
  RESET: 'RESET',
  GET_STORIES: 'GET_STORIES',
  STORE_CREATED_STORY: 'STORE_CREATED_STORY',
  LOGOUT: 'LOGOUT',
  UPDATE_STORY_STATUS: 'UPDATE_STORY_STATUS',
};
