export default {
  LOGIN: 'LOGIN',
  PERSIST_LOGIN: 'PERSIST_LOGIN',
  ACTIVE_ROUTE: 'ACTIVE_ROUTE',
  TOGGLE_SIDE_NAV: 'TOGGLE_SIDE_NAV',
  CREATE_STORY: 'CREATE_STORY',
  RESET_CREATE_STORY_SUCCESS: 'RESET_CREATE_STORY_SUCCESS',
};
